### PR TITLE
Lps 72970

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
@4lejandrito HtmlContentTransformerImpl costs us a lot of time to rewrite the img tag.
This pull is just using a hacky way to avoid regex whenever we can.

Searching through the system, I only see AdaptiveMediaBlogsEntryAttachmentContentUpdater generates such img with "data-fileEntryId" attribute.
Why can't we just make AdaptiveMediaBlogsEntryAttachmentContentUpdater generate the tag in the preferred way in the first place? That could avoid the html generation/reparsing completely.

CC @JorgeFerrer @mhan810

**Comment by shuyangzhou** [comment]
I pushed this one upstream to unblock our optimization process, otherwise that regex overhead is covering all other hotspots.

@4lejandrito please take a look to see if you can move the transformer logic into AdaptiveMediaBlogsEntryAttachmentContentUpdater, so that we can avoid the heavy html parsing.

**Comment by 4lejandrito** [comment]
Hi @shuyangzhou,

There are more places where the transformation is being made. We will consider different approaches to improve performance and hopefully implement a better solution. 

For the moment you can disable the dynamic replacement of images just by stopping the modules `Liferay Adaptive Media Blogs Editor Configuration Dynamic` and `Liferay Adaptive Media Content Transformer API`. This way the picture elements will be generated when the blog entry is created and the content will not be processed on every request.

**Pull request merged**
